#!/bin/bash 

# pacer_dirty_image_test 20191104_033537_eda2_ch1_ant256_midday_avg1 -p _channel000_time000000 -n 2048

# Same two paths (one is symlink to another) :
# path=/home/msok/Desktop/PAWSEY/PaCER/software/imager/pacer_dirty_image/src
# path=/home/msok/github/pacer/software/imager/pacer_dirty_image/build/

gzip -d *.fits.gz
pacer_dirty_imager 20191104_033537_eda2_ch1_ant256_midday_avg1 -p _channel000_time000000 -n 2049 -a antenna_locations.txt -v 0


# compare resulting image with a template :
# calcfits_bg dirty_test_real_fftshift_2049x2049.fits = ../TEMPLATE/dirty_test_real_fftshift_2049x2049.fits


# pacer_dirty_image_test 20191104_033537_eda2_ch1_ant256_midday_avg1 -p _channel000_time000000 -n 1024

# pacer_dirty_image_test 20191104_033537_eda2_ch1_ant256_midday_avg1 -p _channel000_time000000 -n 513
# pacer_dirty_image_test 20191104_033537_eda2_ch1_ant256_midday_avg1 -p _channel000_time000000 -n 512


# pacer_dirty_image_test 20191104_033537_eda2_ch1_ant256_midday_avg1 -p _channel000_time000000 -n 128
# pacer_dirty_image_test 20191104_033537_eda2_ch1_ant256_midday_avg1 -p _channel000_time000000 -n 129
# pacer_dirty_image_test 20191104_033537_eda2_ch1_ant256_midday_avg1 -p _channel000_time000000 -n 160
# pacer_dirty_image_test 20191104_033537_eda2_ch1_ant256_midday_avg1 -p _channel000_time000000 -n 100
# pacer_dirty_image_test 20191104_033537_eda2_ch1_ant256_midday_avg1 -p _channel000_time000000 -n 129

# pacer_dirty_image_test 20191104_033537_eda2_ch1_ant256_midday_avg1 -p _channel000_time000000 -n 64
# pacer_dirty_image_test 20191104_033537_eda2_ch1_ant256_midday_avg1 -p _channel000_time000000 -n 65

# pacer_dirty_image_test 20191104_033537_eda2_ch1_ant256_midday_avg1 -p _channel000_time000000 -n 45


