#!/bin/bash

# /home/msok/github/pacer/software/imager/pacer_dirty_image/src/pacer_dirty_image chan_204_20211116T203000 -f 159.375 -a antenna_locations.txt -n 2049 -w N > 2049.out 2>&1
# /home/msok/github/pacer/software/imager/pacer_dirty_image/src/pacer_dirty_image chan_204_20211116T203000 -f 159.375 -a antenna_locations.txt -n 181 -w N > 181.out 2>&1

# antenna flagging option : -A 0,1,2,3,4,5,6,7,8,9,10
# path=/home/msok/github/pacer/software/imager/pacer_dirty_image/build/

gzip -d *.fits.gz
pacer_dirty_imager chan_204_20211116T203000 -f 159.375 -a antenna_locations.txt -n 180 -w N -v 0 -s > 180.out 2>&1

# compare resulting image with a template :
calcfits_bg dirty_test_real_fftshift_180x180.fits = ../TEMPLATE/dirty_test_real_fftshift_180x180.fits
